### ISSUE TITLE
Support for voiranime.com

### ISSUE THREAD

**Issue by brook91** [lolamtisch/MALSync#136]
Could it be possible ? It's a french-streaming website http://voiranime.com/
If you can't add it, it's ok don't worry

And sorry for posting it on the request page, i don't know how to use github i'm new

**Comment by lolamtisch** [comment]
`Pull request` are for code changes and `issues` are for issues and feature request. 

It is possible to add that page but a bit difficult because of the multi season pages and missing link to the overview page from the video page.

I am kind of slow adding new pages. This prozess could be speed up, if you would help with the french translation of the extension. Just drop by on discord.

**Comment by lolamtisch** [comment]
Included in version 0.6.0
