### ISSUE TITLE
MangaDex "Anime Update Failed"

### ISSUE THREAD

**Issue by Strelok27** [lolamtisch/MALSync#15]
1. Ran into problems with getting Fights Break Sphere to update chapter, the mini mal has all the correct information and links back to the MAL page, however, I get "Anime Update Failed" when it tries to update the chapter. I don't want to waste your time with one manga not updating, however, considering all the data is there then it should update properly. 

2. Might want to change the error message to depending on whether your watching anime or reading manga.

**Comment by lolamtisch** [comment]
2. Thanks will just change it to "Update failed"

1. I just tested it and it updated without a problem.
Could you sent me a copy of the log after the update fails?
https://github.com/lolamtisch/MALSync/wiki/Save-log

**Comment by Strelok27** [comment]
[mangadex.org-1540471880779.log](https://github.com/lolamtisch/MALSync/files/2514931/mangadex.org-1540471880779.log)

**Comment by lolamtisch** [comment]
@Strelok27 
Looks like chromes log saving feature is really useless, because it does not save the minimized accordions. 

Could you sent me the exact url and the parts in the screenshoots?
![image](https://user-images.githubusercontent.com/12599334/47866102-2b23d380-ddfe-11e8-9216-e15a416d9ef8.png)

![image](https://user-images.githubusercontent.com/12599334/47866070-19423080-ddfe-11e8-846b-8a671055622e.png)

**Comment by Strelok27** [comment]
https://mangadex.org/chapter/144346/1 (Just a random chapter from "Fights Break Sphere
")

![weallhatelogs](https://user-images.githubusercontent.com/13710746/48230356-b78f4280-e378-11e8-8020-6016b7b0b02a.PNG)

**Comment by Strelok27** [comment]
Fixed, I changed "Ask to Discuss?" setting to "Don't ask to discuss" and the issue was resolved... you're correct I use to use MAL Updater, Taiga, and Kissanime Essentials. The bad data must've been passed through one of those...
