### ISSUE TITLE
add anilist 

### ISSUE THREAD

**Issue by Zocex** [lolamtisch/MALSync#19]
add anilist to sync scores. i have found that anilist to be better than mal.

also mangadex is better than kissmanga. it has no ads. thank u

**Comment by FunkyJustin** [comment]
I'm trying to migrate to them as I've recently stumbled upon Taiga (https://taiga.moe/), a tool that synchronizes all 3 anime listing websites (MAL, Kitsu and Anilist) unfortunately MAL's API was disabled so it's unable to synchronize with it.

I use Taiga mainly to watch downloaded shows and I use MAL-Sync to watch streamed anime and read manga and the only reason I'm still using MAL is because of this extension. I would love to hear from you as soon as you finish either Kitsu and Anilist support so I can finally migrate :^D

**Comment by lolamtisch** [comment]
I was planning to begin adding anilist after the next release. But it will take quite some time as it is not that straight forward to implement it.

**Comment by Zocex** [comment]
hey as long you are gonna do it eventually, i dont care if it is tomorrow or next year. i am just glad that you are open to the idea of adding this site. for that i thank you good sir.

**Comment by FunkyJustin** [comment]
I've stumbled upon an extension that syncs anilist and kitsu I'm wondering if you guys can collaborate to create one extension to sync all 3? 

Their github page is https://github.com/leonekmi/scrobbly

**Comment by lolamtisch** [comment]
Anilist implementation is stable enought now. 
You will need to switch to anilist mode for it to work
![image](https://user-images.githubusercontent.com/12599334/52418547-93b1d900-2aee-11e9-87f2-833314b1d0f4.png)
