### ISSUE TITLE
Yandex Browser Addon does not install

### ISSUE THREAD

**Issue by JoachimFlottorp** [lolamtisch/MALSync#190]
**Describe the bug**

Basically the addon does not install on the android browser Yandex. It gives the error: Invalid manifest

**Steps to reproduce the behavior:**

Install yandex browser, go to chrome webmarket and install mal sync

**Additional information:**
 - Browser: Yandex
 - Type: Extension
 - Url: https://play.google.com/store/apps/details?id=com.yandex.browser

**Comment by lolamtisch** [comment]
I can reproduce it on my smartphone, but it works without any problems on any of the other browser (Chrome/vivaldi/edge/firefox).
The Problem is a for chrome unknown permission. That permissions is needed/exists in firefox and I use the same manifest and no other browser has a problem with it. I would recommend you try to contact yandex.

Possible workarounds:
* Use Firefox for android
* Install an Userscriptmanager (Ex.: ViolentMonkey) and install the userscript version of mal-sync

Error in Yandex:
![image](https://user-images.githubusercontent.com/12599334/65046905-c021b380-d961-11e9-8ae1-16993c89ce89.png)

**Comment by zakius** [comment]
you can use https://github.com/mozilla/web-ext to simplify releasing packages for different browsers
