### ISSUE TITLE
hyperlink straight to the github page 

### ISSUE THREAD

**Issue by GodIHateThis** [lolamtisch/MALSync#22]
Just like there are bunch of links in the settings section at the bottom

Why not shove in an extra that goes straight to the **main page of this project**

Or another good one:
a button **upgrade** (or something like that) which opens up the releases section of this project.

**Comment by Karmesinrot** [comment]
For the Hyperlink there is already one under the setting on miniMal
![eqm4xxf](https://user-images.githubusercontent.com/32945140/48302622-9a55a200-e539-11e8-99e4-f0bfd78eb1e6.png)

A button for updating the extension is already built-in both on Firefox and Chrome(though you'll have to enable the developer mode on chrome).

As for the change-log only the dev could answer that part.

**Comment by lolamtisch** [comment]
I can add a direct link to the main page of github.

The upgrade button makes less sense because of the different possibilites to update the extension/userscipt. But i would add a releases link to the planned seperate changelog page that will be build in into the extension soon™. 
The current changelog through the releases is only a temporary solution.

**Comment by lolamtisch** [comment]
Github and changelog badge added.
On the changelog page you can click on the version number to get to the github release.
