### ISSUE TITLE
Ability to de auth accounts

### ISSUE THREAD

**Issue by Cwavs** [lolamtisch/MALSync#280]
Allow us to disconnect accounts. E.g Removing MAL to prevent syncing to those sites

**Comment by lolamtisch** [comment]
Simkl and anilist can be revorked from the their page. Kitsu has no option for that so there we are stuck. I will add an Funktion for that then.

Mal btw is techically not possible to be disconnected, because it uses the browser session. That mean the only way to stop it is to log out in the browser from myanimelist.net .

**Comment by TimeHopper** [comment]
Ok,thanks

**Comment by jacobmix** [comment]
Hope next release will come soon. Don't really use Kitsu, and it's by far the one that takes the longest to sync.

**Comment by lolamtisch** [comment]
Added
