### ISSUE TITLE
Mangadex domain change

### ISSUE THREAD

**Issue by eridanired123** [lolamtisch/MALSync#282]
**Describe the bug**
Mangadex recently migrated to a different domain [mangadex.org] -> [mangadex.cc], could MALSync be updated to use this new domain?

**Additional information:**
 - Url: https://mangadex.cc/thread/200708

**Comment by henrik9999** [comment]
the new domain is already added in the code but it can take some time until there is an new release

**Comment by farahnur42** [comment]
@eridanired123 MangaDex staff have also said they are working on getting the .org domain back in the official Discord server, but without any ETA as of right now. The issue here is that while the change can be done, by the time the update is published on the Chrome Web Store MangaDex will likely be back to the old domain so it's best to just wait it out for now.

**Comment by lolamtisch** [comment]
Already added. But the long review processes by Google make it difficult to push fixes fast.

**Comment by eridanired123** [comment]
I use the JS script, so no waiting time for me, ha! =P

Anyway, I'll patiently await for the next release then. Thank you guys!
