### ISSUE TITLE
It seems broken on Microsoft Edge (chromium)

### ISSUE THREAD

**Issue by sprite-1** [lolamtisch/MALSync#288]
**Describe the bug**

I've already subscribed to Anifiltrs on uBlock Origin

![image](https://user-images.githubusercontent.com/33685433/72672928-6b23b480-3a9d-11ea-947a-2696acf1c060.png) ![image](https://user-images.githubusercontent.com/33685433/72672933-770f7680-3a9d-11ea-89ec-b95ae3fa90e0.png)

**Steps to reproduce the behavior:**
Use ViolentMonkey and MALSync script on Microsoft Edge Dev (Chromium)

**Additional information:**
 - Browser: Microsoft Edge (Chromium)
 - Type: Userscript

**Comment by lolamtisch** [comment]
Works fine on my edge with violentmonkey. But seems like it is blocking the css file for you. So probably some kind of adblocker work. Just for testing deactivate all other extension.

Either way i would recommend to use the extension version of mal-sync instead of the userscript. There is even one in the edge store now.

**Comment by sprite-1** [comment]
Weird, I've already disabled

- uBlock Origin
- Privacy Badger
- Decentraleyes
- MS Edge's built in Tracking Protection

And then force refreshed and it still does't work... Do you use the Dev version of the browser?

I have my ViolentMonkey set to sync userscripts and their respective settings across browsers so if I disable it here, it's gonna affect everywhere so I'd like to make it work as much as possible with the Userscript version

**Comment by sprite-1** [comment]
One of the newer updates seem to have fixed it now.
