### ISSUE TITLE
About Manga support

### ISSUE THREAD

**Issue by hemlok89** [lolamtisch/MALSync#29]
Hello, I dont know if this is a feature request but here it goes. I get that this script is geared towards mainly anime but some of us read manga too. It would be helpful if you could add a few more manga site support. MangaRock does not have a bookmark feature so I have to search for manga & check if it is updated. Mangarock does not integrate into MAL. I don't understand why people voted for  this site.

**Comment by lolamtisch** [comment]
Hi,

> It would be helpful if you could add a few more manga site support. 

The Problem with manga pages is that they make much more work, because of the many false recognitions i have to do more to keep the mapping database up to date.

>Mangarock does not integrate into MAL. I don't understand why people voted for this site.

I suppose you mean the links on the sidebar on MAL. They are disabled atm because of the many false mappings in my database (Problem like above). I want to let it settle first before activating it.

> MangaRock does not have a bookmark feature so I have to search for manga [...] 

One of the main purposes of this script is that you dont need the onsite bookmark system, because everything can be handled over MAL.
After starting reading a Manga on mangarock a icon link should show up in your MAL mangalist and on the MAL manga overview page next to the title. It should then take you to the manga page.
The option `Continue watching links` has to be enabled for this to work.

> [...] & check if it is updated. 

If the bookmarks on MAL are working you could try the update check (beta) functionality to get notified, when a new chapter is uploaded.  Important here is that this option is disabled by default and is only available over the extension popup.

**Comment by hemlok89** [comment]
Thank you for your reply. I actually did not notice the auto tracking settings. It makes my life a lot easier. I just tried a new manga from mangarock & MAL is showing a MR logo next to it. But how can I change all the others which have Kissmanga or mangadex logos next to it? Also will autotracking work when I manually update a MAL URL entry?

**Comment by lolamtisch** [comment]
It only updates the url when it autotracks. There is no simple way to manually change the url.
The easiert thing is to open the next chapter on mangarock (Just set the right chapter number again afterwards) and let it autosync. It should then override the kissmanga url.

> Also will autotracking work when I manually update a MAL URL entry?

I am not sure what you mean with that. If you mean to correct a wrong mapped manga to MAL. Then yes. Autotracking should always work.
Or if you mean to change the chapter/rating/state on MAL directly, that is no problem too. btw autotracking only triggers if the open chapter is higher then on MAL.

**Comment by hemlok89** [comment]
Thank you!! Yes, I searched for YotsubaTo! on MR & it is with a different name. So I had to update with the correct MAL url.

**Comment by hemlok89** [comment]
Sorry for re oening this issue. I forgot the most important reason for support for additional manga site. It is true that MAL bookmark acts as a one stop solution but many manga or manhwas dont have any MAL entries. Those need to be bookmarked on the reading site, For example God of Martial Arts, No Guard Wife are some of the more popular mangas on both KM & MR. But they don't have any entries on MAL. For these, I have to rely on Kissmanga bookmark system. That is why I recommended MangaNelo in the first place. It as a great database with pleasant experience. Also a good bookmarking system.

I know adding a new site is difficult work. And I am greatful for this script for what it is. If you are able to add some more manga sites in future, it would be worthwhile for us manga readers.

Thank :)

**Comment by lolamtisch** [comment]
I will add it. But not too soon. I think this issue can be closed as the collecting issue #6 is still open. 

Btw you can always try to request new entries in MAL.
I collected the needed informations for that here. Just read the guideline if the manga is allowed in MAL. They hide the function pretty well 🙄
https://github.com/lolamtisch/MALSync/wiki/MAL-addition

**Comment by hemlok89** [comment]
Thank you for the guide. Yes, it is not so simple to just submit a new entry in MAL. Also sometimes moderators just rejects entries for no apparrent reason.
