### ISSUE TITLE
Can you add turkanime to stream links and search.

### ISSUE THREAD

**Issue by cartals** [lolamtisch/MALSync#30]
can you add turkanime to stream links like this
![ekran alintisi](https://user-images.githubusercontent.com/43301560/50723720-67232f80-10f2-11e9-8294-f342d86b8517.PNG)
![ekran alintisi](https://user-images.githubusercontent.com/43301560/50724367-4b715680-10fd-11e9-88ed-60c90c700075.PNG)

**Comment by lolamtisch** [comment]
@cartals 
The links of the sidebar are generated throw my database.
I did not add turkanime to that database. I am not sure if i will add it someday, because of the much additional work it does.

But i will at least add serach button in the next release to make it easier. 

I am not sure if you noticed it but after starting watching a show on turkanime and auto syncing once it should add a icon with a link to that anime on the overview page on mal and on your bookmarklist next to the title.
![image](https://user-images.githubusercontent.com/12599334/50726431-1ec53b00-110d-11e9-97fc-1122e8f689a1.png)
