### ISSUE TITLE
Continue Watching only appears on currently airing shows

### ISSUE THREAD

**Issue by HyperEpsilon** [lolamtisch/MALSync#319]
After updating to 0.7.1 on both firefox and chrome, the continue watching icons disappeared for shows that have already been completed and only shows up for currently airing shows (Isekai Quartet 2 in my case).

This seems to affect shows on Twist.moe, 9anime, and Kissanime.

![firefox_2020-03-03_15-37-53](https://user-images.githubusercontent.com/6267244/75827053-0d55de00-5d66-11ea-9bf7-668e95ca49d7.png)

-----

Maybe related but my chrome update check debug screen is showing "Episode List Empty" for a a few shows and I don't exactly know why. There was no "continue watching" link next to them before the above bug was happening in the first place

![2020-03-03_15-46-58](https://user-images.githubusercontent.com/6267244/75827175-4db55c00-5d66-11ea-856d-112b53d0ee88.png)

**Comment by lolamtisch** [comment]
Because of mayor changes in the last update we had to clear all current/continue watching data. So it first has to get the links again.
It saves the links when watching the show. You probably watched Isekai Quartet 2 lately and that is why it is showing up. Just continue using it like normal and it should slowly fill up again.

Update check should thetheoretically fill in the links too. But because of the large list of supported pages and just the nature of the things, it is not that reliable.

**Comment by HyperEpsilon** [comment]
Ah, that explains it. Thanks.

When I watched something else the link came back.
