### ISSUE TITLE
Animepahe issue from https://addons.mozilla.org/en-US/firefox/addon/mal-sync/reviews/1512501/

### ISSUE THREAD

**Issue by aasutossh** [lolamtisch/MALSync#345]
Hi, I'm using Firefox Developer Edition (version 75.0b11).

When I click on `Naruto` it takes me to https://animepahe.com/anime/7cc26ad8-4b71-42c8-2ab7-55aeec63982b page, which then shows 404 error.

Actually none of Animepahe's links work from the extension popup.
I don't know if it is clearer, I tried taking screenshot but couldn't.

**Comment by lolamtisch** [comment]
It could be that animepahe updated his urls, resulting in the saved urls not working anymore. If that is the case then we cant do anything against that. If you just start watching that series again it should update the url to the new one. You can only hope that it was an unique event that they changed the urls.

If you want to start fresh without any urls in your list, because they are saved localy, then you could execute the cleaning script behind the `CLEAN TAGS` button in the settings

**Comment by aasutossh** [comment]
Well, I started watching Naruto from animepahe, I did today too. But the extension won't update the urls.

**Comment by henrik9999** [comment]
it seems like animepahe changed its ids not session based ids nothing much we can do about it

**Comment by aasutossh** [comment]
Sorry about bugging you then.
Closing.

**Comment by henrik9999** [comment]
Btw I found a solution to this problem and its added in the latest malsync versions so it should work fine now. Once you updated the links by watching an episode or something of course

**Comment by aasutossh** [comment]
Yeah, it's amazing. Thank you for this.
