### ISSUE TITLE
Addon seems to think My Hero Academia is Major S4 on Crunchyroll

### ISSUE THREAD

**Issue by Dyras** [lolamtisch/MALSync#354]
**Describe the bug**
Greetings! This is probably the wrong place for this, but...
https://myanimelist.net/anime/3226/Major_S4
The addon seems to think that My Hero Academia on Crunchyroll is Major S4. I noticed this when I saw that I had apparently watched every episode of Major S4 even though I have never even heard of it before.

**Steps to reproduce the behavior:**
Click the link and look at the left side. If you watch MHA on Crunchyroll, Major S4 is marked as viewed on your MAL list.

**Additional information:**
 - Browser: Latest Firefox
 - Type: Addon
 - Url: https://myanimelist.net/anime/3226/Major_S4

![grafik](https://user-images.githubusercontent.com/12563436/79239373-c97beb80-7e70-11ea-80d8-44c18e0cf90f.png)

**Comment by lolamtisch** [comment]
You can correct wrong recognitions by hand. Just open the video page (on cr it does not work on the overviewpage because of the mess they have there). Just follow the gif in the first dropdown:

https://github.com/lolamtisch/MALSync/wiki/Troubleshooting#myanimeentry--anilist--kitsu--simkl-entry-is-not-correct
