### ISSUE TITLE
Cmd+Left/Right stops working when Chrome extension is installed

### ISSUE THREAD

**Issue by karrui** [lolamtisch/MALSync#67]
**Describe the bug**
When the MAL-Sync chrome extension is added, Cmd+Left or Cmd+Right stops working on input fields in Chrome. 

**Steps to reproduce the behavior:**

1. Install MAL-Sync
2. Go to any input field (e.g the Omnibar) and type anything
3. Try using Cmd+Left or Cmd+Right to move cursor to front or back of input
4. Be sad when it does not work.
5. Delete MAL-Sync extension
6. Cmd+Left/Right works again

**Additional information:**
 - Browser: Chrome version 73.0.3683.103 64bit
 - Type: Chrome Extension
 - Url: https://chrome.google.com/webstore/detail/mal-sync/kekjfbackdeiabghhcdklcdoekaanoel?hl=en

EDIT:
This may be due to the shortcuts present in the Chrome extension:
<img width="627" alt="Screen Shot 2019-04-19 at 5 49 03 PM" src="https://user-images.githubusercontent.com/22133008/56446999-7d34b480-62cb-11e9-9b11-1dff8588ac17.png">

**Comment by lolamtisch** [comment]
Yeah it is the shortcuts. Looks like chrome overrides the default behaviour. What is kind of dumb. Will change that in the next release. But you can allways change the shortcuts. https://github.com/lolamtisch/MALSync/wiki/Shortcuts

**Comment by stapuft** [comment]
....i dont know if it would help, me and my friends made a userscript for rw/ff
it works on kissanime and 9anime as well as many other sites that use html5 video embeds. the amount of time each skips can be adjusted as can the shortcut keys so that they don't overwrite any shortcuts you already have set up. as they are now though, they do kind of break the netflix and youtube keyboard shortcuts they already have, if you want to stop this just delete these two lines.
"// @include      http://*/*
// @include      https://*/*"


"j"-rewinds 90 seconds
"k"-rewinds 30 seconds
 "l"-fast forwards 30 seconds
 ";"-fast forwards 89 seconds
```
// ==UserScript==
// @name         universal Rewind/FF
// @namespace    http://tampermonkey.net/
// @version      0.5
// @description  Adds extra keyboard shortcuts to html5 videos
// @author       Skillrax & Daehock & v4lt5u
// @include      *://www.rapidvideo.*
// @include      *://mcloud.*
// @include      *://openload.*
// @include      *://streamango.*
// @include      *://prettyfast.to/*
// @include      *://www.mp4upload.com/*
// @include      *://9anime.ru/watch/*
// @include      *://kissanime.ru/Anime/*
// @include      *://kimcartoon.to/Cartoon/*
// @include      *://streamp1ay.me/*
// @include      http://*/*
// @include      https://*/*
// @grant        none
// ==/UserScript==

function rewind(element) {
    element.currentTime -= 91;
}

function rewind2(element) {
    element.currentTime -= 30;
}

function skip(element) {
    element.currentTime += 89;
}

function skip2(element) {
    element.currentTime += 30;
}

window.addEventListener('keypress', (event)=>{
    if (event.key == "j") {
        rewind(document.getElementsByTagName("video")[0]);
    } else if (event.key == ";") {
        skip(document.getElementsByTagName("video")[0]);
    }else if (event.key == "l") {
        skip2(document.getElementsByTagName("video")[0]);
    }else if (event.key == "k") {
        rewind2(document.getElementsByTagName("video")[0]);
    }
});
```

i am posting this here because i figure why not, if you would like to use this code @lolamtisch feel free, same goes for anyone else just dont forget the people that made it.

**Comment by lolamtisch** [comment]
@stapuft
Thanks. But I already have a script for that too. ;) 
https://greasyfork.org/en/scripts/33779-intro-skipper
I am using the extension shortcuts, because they can easily remapped by the user and are easy to implement. 

I am just going to remove the default mapping. If the user wants to use the feature he will have to map them himself to what ever he wants first. I like the cntr+arrow-key and I never use word jumping. So that is not a problem for me.

**Comment by stapuft** [comment]
@lolamtisch ok i didnt realize, and ours is user configurable aswell, just replace the "key" in quotes in the event.key section with whatever keys you want you can even configure it to custom times by changing the number in the element.currentTime line

that seems like a good compromise man, and honestly, i dont either, i didnt even know it was a thing untill this post.

**Comment by lolamtisch** [comment]
Removed default keys in newsest release

**Comment by HyperEpsilon** [comment]
Took me forever to figure out why my Ctrl + Arrows had stopped working as I use them almost daily for text editing. Is there no way to only have them effect the video player and not the entirety of chrome? Something like youtube where the keyboard shortcuts only do something if you're focused on the video?

I've changed my shortcuts to Alt + Shift + Arrows as I don't think that conflicts with anything, but I think that overriding a common shortcut by default is a little discourteous.

**Comment by lolamtisch** [comment]
@HyperEpsilon
I agree it is very dumb that it works like that. As stated I removed the default keys some months ago. But it does not remove it for people that had the extension installed before that update, as the default remains and I cant do anything against it. 

It is not possible to fix that behaviour with the chrome shortcut API. But there are ways around that, I just didn't have the time to implement it. As it has to be be build from the ground up.

**Comment by InsaneDoggo** [comment]
I've faced similar issues with hotkeys while developing my extension, so I've opened corresponding ticket for chrome's API. https://issues.chromium.org/issues/364821285 feel free to "vote up"

**Comment by lolamtisch** [comment]
@InsaneDoggo We switched to just listening for keypresses on the websites directly without any api. So we do not run into this problem anymore.
